// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpfWv5gge05GMqnzJjes6n3OceVVexjwk',
    appId: '1:873005738690:web:f247ad52d9f5027851295b',
    messagingSenderId: '873005738690',
    projectId: 'sequence-mate',
    authDomain: 'sequence-mate.firebaseapp.com',
    storageBucket: 'sequence-mate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVSk9bBxNIbGrQQoczto7x78D00EsTIo',
    appId: '1:873005738690:android:ded704eefba08d1c51295b',
    messagingSenderId: '873005738690',
    projectId: 'sequence-mate',
    storageBucket: 'sequence-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5wUKJOziiYZVuQUQWjy09O6_Ls7W1UHg',
    appId: '1:873005738690:ios:4f73521cc10826f851295b',
    messagingSenderId: '873005738690',
    projectId: 'sequence-mate',
    storageBucket: 'sequence-mate.appspot.com',
    iosClientId: '873005738690-8brm7da56ofn1gldecamumjtsk9e1cgn.apps.googleusercontent.com',
    iosBundleId: 'com.dhui.flutterPractice',
  );
}
